version: "3.8"
services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "3006:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
    volumes:
      - data_postgresql:/var/lib/postgresql/data
volumes:
  data_postgresql: